# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo-Z710.xdc

# Block Designs: bd/racaster_test/racaster_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test || ORIG_REF_NAME==racaster_test} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_clock_div_25_0_0/racaster_test_clock_div_25_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_clock_div_25_0_0 || ORIG_REF_NAME==racaster_test_clock_div_25_0_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_rgb2dvi_0_0/racaster_test_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_rgb2dvi_0_0 || ORIG_REF_NAME==racaster_test_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_xlconstant_0_0/racaster_test_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_xlconstant_0_0 || ORIG_REF_NAME==racaster_test_xlconstant_0_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_xlconstant_0_1/racaster_test_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_xlconstant_0_1 || ORIG_REF_NAME==racaster_test_xlconstant_0_1} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_xlconcat_0_0/racaster_test_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_xlconcat_0_0 || ORIG_REF_NAME==racaster_test_xlconcat_0_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_vga_ctrl_0_0/racaster_test_vga_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_vga_ctrl_0_0 || ORIG_REF_NAME==racaster_test_vga_ctrl_0_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_pixel_pusher_0_0/racaster_test_pixel_pusher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_pixel_pusher_0_0 || ORIG_REF_NAME==racaster_test_pixel_pusher_0_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_processing_system7_0_3/racaster_test_processing_system7_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_processing_system7_0_3 || ORIG_REF_NAME==racaster_test_processing_system7_0_3} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_axi_bram_ctrl_0_0/racaster_test_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_axi_bram_ctrl_0_0 || ORIG_REF_NAME==racaster_test_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_axi_bram_ctrl_0_bram_0/racaster_test_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==racaster_test_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_xlconstant_2_0/racaster_test_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_xlconstant_2_0 || ORIG_REF_NAME==racaster_test_xlconstant_2_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_axi_smc_0/racaster_test_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_axi_smc_0 || ORIG_REF_NAME==racaster_test_axi_smc_0} -quiet] -quiet

# IP: bd/racaster_test/ip/racaster_test_rst_ps7_0_100M_0/racaster_test_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==racaster_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==racaster_test_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/keyur/Documents/Vivado/raycaster_test/raycaster_test.gen/sources_1/bd/racaster_test/racaster_test_ooc.xdc
